name: "Release"

on:
  push:
    tags: 
        ['\*']

  workflow_dispatch:

permissions:
  contents: read 
      
jobs: 
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm

    steps:
    - uses: actions/checkout@v4
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.200

    # if not using any workloads (e.g, Aspire, Wasm, Maui), remove this step
    - name: Restore workloads
      run: dotnet workload restore
   
    - name: Download Cielo Android SDK
      run: |
         sudo apt-get update
         sudo apt-get install -y curl unzip
         curl https://desenvolvedores.cielo.com.br/api-portal/sites/default/files/ctools/SDK-2.0.1.zip -o cielo.zip
         unzip cielo.zip
         mkdir -p ${{ github.workspace }}/src/CieloLio.Bindings/src/CieloLio.NET/Jars
         mv SDK-2.0.1/com/cielo/lio/order-manager/order-manager.aar ${{ github.workspace }}/src/CieloLio.Bindings/src/CieloLio.NET/Jars/order-manager.aar
         
    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore
       
    